SELECT * FROM hr_analytics.`wa_fn-usec_-hr-employee-attrition`;

USE HR_ANALYTICS;

ALTER TABLE `wa_fn-usec_-hr-employee-attrition`
RENAME TO hr_attrition;

SELECT * FROM HR_ATTRITION;

-- Categorized Employees into Salary Bands

SELECT EMPLOYEENUMBER , MONTHLYINCOME,
CASE
WHEN MONTHLYINCOME < 5000 THEN "LOW SALARY"
WHEN MONTHLYINCOME < 10000 THEN "MEDIUM SALARY"
ELSE "HIGH SALARY"
END AS SALARY_BAND
FROM HR_ATTRITION;

-- Counted Attrition by Marital Status in a Single Row

SELECT
sum(CASE WHEN MARITALSTATUS = "SINGLE" AND ATTRITION = "YES" THEN 1 ELSE 0 END ) AS SINGLE_LEFT,
SUM(CASE WHEN MARITALSTATUS = "MARRIED" AND ATTRITION = "YES" THEN 1 ELSE 0 END) AS MARRIED_LEFT,
SUM(CASE WHEN MARITALSTATUS = "DIVORCED" AND ATTRITION = "YES" THEN 1 ELSE 0 END)AS DIVORCED_LEFT
FROM HR_ATTRITION;
 
 -- Compared Average Salary of Male vs Female Employees by Department
 
 SELECT DEPARTMENT,
 ROUND(AVG(CASE WHEN GENDER = "MALE" THEN MONTHLYINCOME END),0) AS MALE_AVG_SALARY,
 ROUND(AVG(CASE WHEN GENDER = "FEMALE" THEN MONTHLYINCOME END),0) AS FEMALE_AVG_SALARY
 FROM HR_ATTRITION
 GROUP BY DEPARTMENT;
 
 -- Calculated Department-wise Employee Distribution Percentage
 
 SELECT DEPARTMENT,
 COUNT(*) AS EMPLOYEES_COUNT,
 ROUND(COUNT(*)* 100.0 / (SELECT COUNT(*) FROM HR_ATTRITION),2) AS EMPLOYEE_PERCENTAGE
 FROM HR_ATTRITION
 GROUP BY DEPARTMENT;

